### ISSUE TITLE
[MC UPDATE] 1.20.5 incompatibility

### ISSUE THREAD

**Issue by krafg** [rdvdev2/DisableCustomWorldsAdvice#16]
- Affected Minecraft version(s): 1.20.5
- Does the game load? Yes
- Does the game crash when creating a world? Yes
- Does the game crash when loading a world? Yes

**Other information**

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-04-23 18:22:53
Description: mouseClicked event handler

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7196 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_310.method_41735(class_310.java:2185)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:434)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:411)
	at net.minecraft.class_350.method_25402(class_350.java:306)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:236)
	at net.minecraft.class_310.method_1523(class_310.java:1345)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 25 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [disable_custom_worlds_advice.mixins.json:MixinIntegratedServerLoader from mod disable_custom_worlds_advice] from phase [DEFAULT] in config [disable_custom_worlds_advice.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on removeAdviceOnLoad could not find any targets matching 'Lnet/minecraft/class_7196;method_54614(Lnet/minecraft/class_32$class_5143;Lcom/mojang/serialization/Dynamic;ZZLjava/lang/Runnable;)V' in net.minecraft.class_7196. Using refmap DisableCustomWorldsAdvice-refmap.json [PREINJECT Applicator Phase -> disable_custom_worlds_advice.mixins.json:MixinIntegratedServerLoader from mod disable_custom_worlds_advice -> Prepare Injections ->  -> localvar$zzo000$disable_custom_worlds_advice$removeAdviceOnLoad(Z)Z -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_310.method_41735(class_310.java:2185)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:434)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:411)
	at net.minecraft.class_350.method_25402(class_350.java:306)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:236)
	at net.minecraft.class_310.method_1523(class_310.java:1345)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 27.639s
	Wall uptime: 18.182s
	High-res time: 16.812s
	Client ticks: 190 ticks / 9.500s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterpingdisplay, cloth-config, continuity, dark-loading-screen, disable_custom_worlds_advice, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, jade, logical_zoom, modmenu, sodium, sound_physics_remastered, tectonic, file/GUI_Patrix_1.20.4.zip, file/FreshAnimations_v1.9.zip, continuity:glass_pane_culling_fix, continuity:default

-- System Details --
Details:
	Minecraft Version: 1.20.5
	Minecraft Version ID: 1.20.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 352472984 bytes (336 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MB): 12272.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.24027.1012
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38814.99
	Virtual memory used (MB): 17810.86
	Swap memory total (MB): 22528.00
	Swap memory used (MB): 150.14
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterpingdisplay: Better Ping Display 1.1.1
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.2
		dark-loading-screen: Dark Loading Screen 1.6.14
		disable_custom_worlds_advice: Disable Custom Worlds Advice 5.0
		fabric-api: Fabric API 0.97.6+1.20.5
			fabric-api-base: Fabric API Base 0.4.40+80f8cf510d
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72b0d
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.24+76551cf60d
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9b0d
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf510d
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf510d
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5b0d
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366f0d
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf510d
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b30d
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.4+b82b23920d
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.3+7f945d5b0d
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.0.0+2b43c5c80d
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf510d
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.15+2a2c66b60d
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.0.5+7f945d5b0d
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+947939130d
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72b0d
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b30d
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf510d
			fabric-item-api-v1: Fabric Item API (v1) 8.1.1+17e985d60d
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.38+aae0949a0d
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf510d
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b30d
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b30d
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.4+97f703da0d
			fabric-message-api-v1: Fabric Message API (v1) 6.0.10+109a837c0d
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf510d
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a70d
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.7+9342ba640d
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.3+c5fc38b30d
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b30d
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.2+c5fc38b30d
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.14+f1240ba70d
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703da0d
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf510d
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b30d
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2e0d
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869ded0d
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b30d
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cb0d
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.0.1+74e2f5600d
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.0.5+c5f2432c0d
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8a0d
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.71+b21c00cb0d
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b30d
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b30d
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f5600d
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		iris: Iris 1.7.0+mc1.20.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 14.0.1+fabric
		java: OpenJDK 64-Bit Server VM 21
		logical_zoom: Logical Zoom 0.0.22
		minecraft: Minecraft 1.20.5
		modmenu: Mod Menu 10.0.0-beta.1
		sodium: Sodium 0.5.8+mc1.20.5
		sound_physics_remastered: Sound Physics Remastered 1.20.4-1.3.1
		tectonic: Tectonic 2.3.4
	Loaded Shaderpack: photon_v1.0a.zip
		Profile: Custom (+22 options changed by user)
	Launched Version: fabric-loader-0.15.10-1.20.5
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon RX 6700 XT GL version 3.2.0 Core Profile Context 24.3.1.240312, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 6/6 chunks
	Resource Packs: vanilla, fabric, betterpingdisplay, cloth-config, continuity, dark-loading-screen, disable_custom_worlds_advice, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, iris, jade (incompatible), logical_zoom, modmenu, sodium, sound_physics_remastered, tectonic (incompatible), file/GUI_Patrix_1.20.4.zip (incompatible), file/FreshAnimations_v1.9.zip (incompatible), continuity:glass_pane_culling_fix (incompatible), continuity:default (incompatible)
	Current Language: en_us
	Locale: es_CL
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor

**Comment by naritanara** [comment]
Thank you for posting the issue. After taking a look at the crash report, I've noticed that you have other mods loaded. Could you try to run the mod without any other mod installed alongside it? Please attach the crash report that you then get, as it will be easier to use for the mod update.

**Comment by krafg** [comment]
[crash-2024-04-26_00.25.41-client.txt](https://github.com/rdvdev2/DisableCustomWorldsAdvice/files/15125324/crash-2024-04-26_00.25.41-client.txt)

Running only this mod with Tectonic (That makes the custom world advice appears).

**Comment by naritanara** [comment]
Thank you very much, I will look at this during the weekend and hopefully submit a patch.

**Comment by krafg** [comment]
Thanks a lot to you, your mod is very usefull to all people that uses any biome/terrain mod on Minecraft. ❤

**Comment by naritanara** [comment]
Fixed with v6.0
